#pragma once

#define ENCODER_BTN_PIN GP10

// Explicit WS2812 / RGBLight configuration.
#define WS2812_DI_PIN GP29
#define RGBLIGHT_LED_COUNT 21
#define RGBLIGHT_LIMIT_VAL 120
#define RGBLIGHT_DEFAULT_HUE 149
#define RGBLIGHT_DEFAULT_SAT 255
#define RGBLIGHT_DEFAULT_VAL 40

// VIA custom lighting UI + persistent settings.
#define VIA_FIRMWARE_VERSION 1
#define EECONFIG_USER_DATA_SIZE 16
#define EECONFIG_USER_DATA_VERSION 1

#define USB_SUSPEND_WAKEUP_DELAY 0
#define DEBOUNCE 5
