BOOTLOADER = rp2040

ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes
RGBLIGHT_ENABLE = yes
VIA_ENABLE = yes
LTO_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = no
AUDIO_ENABLE = no
OLED_ENABLE = no
BACKLIGHT_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

WS2812_DRIVER = vendor
